<?php

namespace frontend\models;


use Yii;

/**
 * This is the model class for table "apitest".
 *
 * @property int $id
 * @property string $name
 * @property string $model
 * @property string $time
 */

class Apitest extends \yii\db\ActiveRecord
{

    const SCENARIO_CREATE = 'create';
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'apitest';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'model'], 'required'],
            [['time'], 'safe'],
            [['name'], 'string', 'max' => 1000],
            [['model'], 'string', 'max' => 100],
        ];

    }

    public function scenarios()
    {
        $scenarios = parent::scenarios();
        $scenarios['create']=['name','model'];
        return parent::scenarios(); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'name' => Yii::t('app', 'Name'),
            'model' => Yii::t('app', 'Model'),
            'time' => Yii::t('app', 'Time'),
        ];
    }
}
